services:
  - type: web
    name: portfolio
    env: node
    buildCommand: NODE_ENV=development npm install && npm run build && npm audit fix --force
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
      - key: NODE_OPTIONS
        value: "--max_old_space_size=1536" 