services:
  - type: web
    name: portfolio
    env: node
    buildCommand: npm install && npm run render-build
    startCommand: npm start
    region: oregon
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_RENDER_DEPLOYMENT
        value: true
    healthCheckPath: /
    autoDeploy: true 